### ISSUE TITLE
Exit Code 1 Crash upon starting up the game (1.20.1)

### ISSUE THREAD

**Issue by Stellar-Seeker** [teamauroramods/EnhancedMushrooms#9] opened 2024-05-12 17:54 UTC
After I downloaded the new version of Enhanced Mushrooms for 1.20.1 and attempted to start the game, the game booted up, attempted to load the mods, and then crashed back to the launcher with an Exit Code 1 crash message. Disabling or removing the mod does not solve the issue.

**Comment by NotAPotter** [comment] 2024-05-12 18:49
Same issue, believe it's some direct and infamous incompatibility on the part of pollen, but I don't know what it is.

**Comment by abby-cadabra** [comment] 2024-05-12 23:28
Confirmed on 1.20.1 Forge.

**Comment by ex0planetary** [comment] 2024-05-13 15:09
> Same issue, believe it's some direct and infamous incompatibility on the part of pollen, but I don't know what it is.

Are you all running Pollen? The new version requires Blueprint.

**Comment by Stellar-Seeker** [comment] 2024-05-13 17:09
> > Same issue, believe it's some direct and infamous incompatibility on the part of pollen, but I don't know what it is.
> 
> Are you all running Pollen? The new version requires Blueprint.

While I can't speak for everyone with this issue, I'm running Blueprint.

However, while examining my modlist I noticed that pollen was installed (despite it not being on 1.20.1), and I think that's the problem.

Uninstalling Pollen fixed the issue entirely.

**Comment by ex0planetary** [comment] 2024-05-13 18:10
Yeah. That sounds about right, given that NotAPotter also mentioned Pollen I'd imagine this is what's going on for everyone. I'll make an announcement in the Discord server - Pollen def won't work if you're on 1.20.1 since it's not available for that version.

Closing this issue since I think it's resolved.

**Closed as completed by ex0planetary** 2024-05-13 18:10 UTC

**Comment by hipsterjazzbo** [comment] 2024-07-23 01:06
I believe this is still happening for some because for some reason curseforge app is auto-installing Pollen when you add Enhanced Mushrooms to a mod pack

**Comment by Sixdd6** [comment] 2024-07-25 12:43
Just installed the 1.20.1 version of the mod and CurseForge is still installing Pollen alongside Blueprint. This really should be fixed as the average user is probably going to install 100 mods at once and not know which mod the problem is caused by since the game will crash before a crashlog can be generated.

**Comment by ex0planetary** [comment] 2024-07-25 21:48
Thanks for the heads-up folks. Turns out the Pollen dependency snuck through on the CurseForge files somehow so it was automatically getting installed alongside the mod. Should be fixed now (just updated the settings on CurseForge so no new update to the mod jar itself).
